"use client";

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { http, createConfig } from "wagmi";
import { bsc } from "wagmi/chains";
import { injected, metaMask, walletConnect } from "wagmi/connectors";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WalletProvider } from "@/context/useWallet";
const WagmiProvider = dynamic(
  () => import("wagmi").then((mod) => mod.WagmiProvider),
  { ssr: false }
);

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

const config = createConfig({
  chains: [bsc],
  connectors: [
    injected(),
    metaMask(),
    walletConnect({ projectId: "a1970e69f049bbfc7dec9ed0b818a703" }),
  ],
  transports: {
    [bsc.id]: http(),
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://telegram.org/js/telegram-web-app.js"
        ></script>
      </head>
      <body className={`${raleway.variable} antialiased`}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={queryClient}>
            <WalletProvider>
            {children}
            </WalletProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
