"use client";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { WalletProvider } from "@/context/useWallet";

const WagmiConfig = dynamic(() => import("@/utils/WagmiConfig"), {
  ssr: false,
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <WagmiConfig>
          <WalletProvider>{children}</WalletProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}