"use client";

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
const Providers = dynamic(() => import("../utils/providers").then(mod => mod.Providers), {
  ssr: false, // Disable SSR for this component
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}